<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          $countries = [
            ['name' => 'Afghanistan','description' => '', 'image_url' => null],
            ['name' => 'Albania','description' => '', 'image_url' => null],
            ['name' => 'Algeria','description' => '', 'image_url' => null],
            ['name' => 'Andorra','description' => '', 'image_url' => null],
            ['name' => 'Angola','description' => '', 'image_url' => null],
            ['name' => 'Antigua and Barbuda','description' => '', 'image_url' => null],
            ['name' => 'Argentina','description' => '', 'image_url' => null],
            ['name' => 'Armenia','description' => '', 'image_url' => null],
            ['name' => 'Australia','description' => '', 'image_url' => null],
            ['name' => 'Austria','description' => '', 'image_url' => null],
            ['name' => 'Azerbaijan','description' => '', 'image_url' => null],
            ['name' => 'Bahamas','description' => '', 'image_url' => null],
            ['name' => 'Bahrain','description' => '', 'image_url' => null],
            ['name' => 'Bangladesh','description' => '', 'image_url' => null],
            ['name' => 'Barbados','description' => '', 'image_url' => null],
            ['name' => 'Belarus','description' => '', 'image_url' => null],
            ['name' => 'Belgium','description' => '', 'image_url' => null],
            ['name' => 'Belize','description' => '', 'image_url' => null],
            ['name' => 'Benin','description' => '', 'image_url' => null],
            ['name' => 'Bhutan','description' => '', 'image_url' => null],
            ['name' => 'Bolivia','description' => '', 'image_url' => null],
            ['name' => 'Bosnia and Herzegovina','description' => '', 'image_url' => null],
            ['name' => 'Botswana','description' => '', 'image_url' => null],
            ['name' => 'Brazil','description' => '', 'image_url' => null],
            ['name' => 'Brunei','description' => '', 'image_url' => null],
            ['name' => 'Bulgaria','description' => '', 'image_url' => null],
            ['name' => 'Burkina Faso','description' => '', 'image_url' => null],
            ['name' => 'Burundi','description' => '', 'image_url' => null],
            ['name' => 'Cabo Verde','description' => '', 'image_url' => null],
            ['name' => 'Cambodia','description' => '', 'image_url' => null],
            ['name' => 'Cameroon','description' => '', 'image_url' => null],
            ['name' => 'Canada','description' => '', 'image_url' => null],
            ['name' => 'Central African Republic','description' => '', 'image_url' => null],
            ['name' => 'Chad','description' => '', 'image_url' => null],
            ['name' => 'Chile','description' => '', 'image_url' => null],
            ['name' => 'China','description' => '', 'image_url' => null],
            ['name' => 'Colombia','description' => '', 'image_url' => null],
            ['name' => 'Comoros','description' => '', 'image_url' => null],
            ['name' => 'Congo (Congo-Brazzaville)','description' => '', 'image_url' => null],
            ['name' => 'Costa Rica','description' => '', 'image_url' => null],
            ['name' => 'Croatia','description' => '', 'image_url' => null],
            ['name' => 'Cuba','description' => '', 'image_url' => null],
            ['name' => 'Cyprus','description' => '', 'image_url' => null],
            ['name' => 'Czechia (Czech Republic)','description' => '', 'image_url' => null],
            ['name' => 'Democratic Republic of the Congo','description' => '', 'image_url' => null],
            ['name' => 'Denmark','description' => '', 'image_url' => null],
            ['name' => 'Djibouti','description' => '', 'image_url' => null],
            ['name' => 'Dominica','description' => '', 'image_url' => null],
            ['name' => 'Dominican Republic','description' => '', 'image_url' => null],
            ['name' => 'Ecuador','description' => '', 'image_url' => null],
            ['name' => 'Egypt','description' => '', 'image_url' => null],
            ['name' => 'El Salvador','description' => '', 'image_url' => null],
            ['name' => 'Equatorial Guinea','description' => '', 'image_url' => null],
            ['name' => 'Eritrea','description' => '', 'image_url' => null],
            ['name' => 'Estonia','description' => '', 'image_url' => null],
            ['name' => 'Eswatini (fmr. "Swaziland")','description' => '', 'image_url' => null],
            ['name' => 'Ethiopia','description' => '', 'image_url' => null],
            ['name' => 'Fiji','description' => '', 'image_url' => null],
            ['name' => 'Finland','description' => '', 'image_url' => null],
            ['name' => 'France','description' => '', 'image_url' => null],
            ['name' => 'Gabon','description' => '', 'image_url' => null],
            ['name' => 'Gambia','description' => '', 'image_url' => null],
            ['name' => 'Georgia','description' => '', 'image_url' => null],
            ['name' => 'Germany','description' => '', 'image_url' => null],
            ['name' => 'Ghana','description' => '', 'image_url' => null],
            ['name' => 'Greece','description' => '', 'image_url' => null],
            ['name' => 'Grenada','description' => '', 'image_url' => null],
            ['name' => 'Guatemala','description' => '', 'image_url' => null],
            ['name' => 'Guinea','description' => '', 'image_url' => null],
            ['name' => 'Guinea-Bissau','description' => '', 'image_url' => null],
            ['name' => 'Guyana','description' => '', 'image_url' => null],
            ['name' => 'Haiti','description' => '', 'image_url' => null],
            ['name' => 'Honduras','description' => '', 'image_url' => null],
            ['name' => 'Hungary','description' => '', 'image_url' => null],
            ['name' => 'Iceland','description' => '', 'image_url' => null],
            ['name' => 'India','description' => '', 'image_url' => null],
            ['name' => 'Indonesia','description' => '', 'image_url' => null],
            ['name' => 'Iran','description' => '', 'image_url' => null],
            ['name' => 'Iraq','description' => '', 'image_url' => null],
            ['name' => 'Ireland','description' => '', 'image_url' => null],
            ['name' => 'Israel','description' => '', 'image_url' => null],
            ['name' => 'Italy','description' => '', 'image_url' => null],
            ['name' => 'Jamaica','description' => '', 'image_url' => null],
            ['name' => 'Japan','description' => '', 'image_url' => null],
            ['name' => 'Jordan','description' => '', 'image_url' => null],
            ['name' => 'Kazakhstan','description' => '', 'image_url' => null],
            ['name' => 'Kenya','description' => '', 'image_url' => null],
            ['name' => 'Kiribati','description' => '', 'image_url' => null],
            ['name' => 'Kuwait','description' => '', 'image_url' => null],
            ['name' => 'Kyrgyzstan','description' => '', 'image_url' => null],
            ['name' => 'Laos','description' => '', 'image_url' => null],
            ['name' => 'Latvia','description' => '', 'image_url' => null],
            ['name' => 'Lebanon','description' => '', 'image_url' => null],
            ['name' => 'Lesotho','description' => '', 'image_url' => null],
            ['name' => 'Liberia','description' => '', 'image_url' => null],
            ['name' => 'Libya','description' => '', 'image_url' => null],
            ['name' => 'Liechtenstein','description' => '', 'image_url' => null],
            ['name' => 'Lithuania','description' => '', 'image_url' => null],
            ['name' => 'Luxembourg','description' => '', 'image_url' => null],
            ['name' => 'Madagascar','description' => '', 'image_url' => null],
            ['name' => 'Malawi','description' => '', 'image_url' => null],
            ['name' => 'Malaysia','description' => '', 'image_url' => null],
            ['name' => 'Maldives','description' => '', 'image_url' => null],
            ['name' => 'Mali','description' => '', 'image_url' => null],
            ['name' => 'Malta','description' => '', 'image_url' => null],
            ['name' => 'Marshall Islands','description' => '', 'image_url' => null],
            ['name' => 'Mauritania','description' => '', 'image_url' => null],
            ['name' => 'Mauritius','description' => '', 'image_url' => null],
            ['name' => 'Mexico','description' => '', 'image_url' => null],
            ['name' => 'Micronesia','description' => '', 'image_url' => null],
            ['name' => 'Moldova','description' => '', 'image_url' => null],
            ['name' => 'Monaco','description' => '', 'image_url' => null],
            ['name' => 'Mongolia','description' => '', 'image_url' => null],
            ['name' => 'Montenegro','description' => '', 'image_url' => null],
            ['name' => 'Morocco','description' => '', 'image_url' => null],
            ['name' => 'Mozambique','description' => '', 'image_url' => null],
            ['name' => 'Myanmar (formerly Burma)','description' => '', 'image_url' => null],
            ['name' => 'Namibia','description' => '', 'image_url' => null],
            ['name' => 'Nauru','description' => '', 'image_url' => null],
            ['name' => 'Nepal','description' => '', 'image_url' => null],
            ['name' => 'Netherlands','description' => '', 'image_url' => null],
            ['name' => 'New Zealand','description' => '', 'image_url' => null],
            ['name' => 'Nicaragua','description' => '', 'image_url' => null],
            ['name' => 'Niger','description' => '', 'image_url' => null],
            ['name' => 'Nigeria','description' => '', 'image_url' => null],
            ['name' => 'North Korea','description' => '', 'image_url' => null],
            ['name' => 'North Macedonia','description' => '', 'image_url' => null],
            ['name' => 'Norway','description' => '', 'image_url' => null],
            ['name' => 'Oman','description' => '', 'image_url' => null],
            ['name' => 'Pakistan','description' => '', 'image_url' => null],
            ['name' => 'Palau','description' => '', 'image_url' => null],
            ['name' => 'Palestine State','description' => '', 'image_url' => null],
            ['name' => 'Panama','description' => '', 'image_url' => null],
            ['name' => 'Papua New Guinea','description' => '', 'image_url' => null],
            ['name' => 'Paraguay','description' => '', 'image_url' => null],
            ['name' => 'Peru','description' => '', 'image_url' => null],
            ['name' => 'Philippines','description' => '', 'image_url' => null],
            ['name' => 'Poland','description' => '', 'image_url' => null],
            ['name' => 'Portugal','description' => '', 'image_url' => null],
            ['name' => 'Qatar','description' => '', 'image_url' => null],
            ['name' => 'Romania','description' => '', 'image_url' => null],
            ['name' => 'Russia','description' => '', 'image_url' => null],
            ['name' => 'Rwanda','description' => '', 'image_url' => null],
            ['name' => 'Saint Kitts and Nevis','description' => '', 'image_url' => null],
            ['name' => 'Saint Lucia','description' => '', 'image_url' => null],
            ['name' => 'Saint Vincent and the Grenadines','description' => '', 'image_url' => null],
            ['name' => 'Samoa','description' => '', 'image_url' => null],
            ['name' => 'San Marino','description' => '', 'image_url' => null],
            ['name' => 'Sao Tome and Principe','description' => '', 'image_url' => null],
            ['name' => 'Saudi Arabia','description' => '', 'image_url' => null],
            ['name' => 'Senegal','description' => '', 'image_url' => null],
            ['name' => 'Serbia','description' => '', 'image_url' => null],
            ['name' => 'Seychelles','description' => '', 'image_url' => null],
            ['name' => 'Sierra Leone','description' => '', 'image_url' => null],
            ['name' => 'Singapore','description' => '', 'image_url' => null],
            ['name' => 'Slovakia','description' => '', 'image_url' => null],
            ['name' => 'Slovenia','description' => '', 'image_url' => null],
            ['name' => 'Solomon Islands','description' => '', 'image_url' => null],
            ['name' => 'Somalia','description' => '', 'image_url' => null],
            ['name' => 'South Africa','description' => '', 'image_url' => null],
            ['name' => 'South Korea','description' => '', 'image_url' => null],
            ['name' => 'South Sudan','description' => '', 'image_url' => null],
            ['name' => 'Spain','description' => '', 'image_url' => null],
            ['name' => 'Sri Lanka','description' => '', 'image_url' => null],
            ['name' => 'Sudan','description' => '', 'image_url' => null],
            ['name' => 'Suriname','description' => '', 'image_url' => null],
            ['name' => 'Sweden','description' => '', 'image_url' => null],
            ['name' => 'Switzerland','description' => '', 'image_url' => null],
            ['name' => 'Syria','description' => '', 'image_url' => null],
            ['name' => 'Tajikistan','description' => '', 'image_url' => null],
            ['name' => 'Tanzania','description' => '', 'image_url' => null],
            ['name' => 'Thailand','description' => '', 'image_url' => null],
            ['name' => 'Timor-Leste','description' => '', 'image_url' => null],
            ['name' => 'Togo','description' => '', 'image_url' => null],
            ['name' => 'Tonga','description' => '', 'image_url' => null],
            ['name' => 'Trinidad and Tobago','description' => '', 'image_url' => null],
            ['name' => 'Tunisia','description' => '', 'image_url' => null],
            ['name' => 'Turkey','description' => '', 'image_url' => null],
            ['name' => 'Turkmenistan','description' => '', 'image_url' => null],
            ['name' => 'Tuvalu','description' => '', 'image_url' => null],
            ['name' => 'Uganda','description' => '', 'image_url' => null],
            ['name' => 'Ukraine','description' => '', 'image_url' => null],
            ['name' => 'United Arab Emirates','description' => '', 'image_url' => null],
            ['name' => 'United Kingdom','description' => '', 'image_url' => null],
            ['name' => 'United States','description' => '', 'image_url' => null],
            ['name' => 'Uruguay','description' => '', 'image_url' => null],
            ['name' => 'Uzbekistan','description' => '', 'image_url' => null],
            ['name' => 'Vanuatu','description' => '', 'image_url' => null],
            ['name' => 'Vatican City','description' => '', 'image_url' => null],
            ['name' => 'Venezuela','description' => '', 'image_url' => null],
            ['name' => 'Vietnam','description' => '', 'image_url' => null],
            ['name' => 'Yemen','description' => '', 'image_url' => null],
            ['name' => 'Zambia','description' => '', 'image_url' => null],
            ['name' => 'Zimbabwe''description' => '', 'image_url' => null],
        ];

        DB::table('countries')->insert($countries);
    }
}
